feat: display version
Mergifyio/mergify-cli pull request #311
Opened 2023-12-24 14:51 UTC by DouglasBlackwood

Change-Id: Ib570059d9cac586c84d2ca099de19614f741f112

Depends-On: #310

2023-12-24 14:51 UTC, DouglasBlackwood commented
This pull request is part of a stack:
1. ci: store version ([#310](https://github.com/Mergifyio/mergify-cli/pull/310))
1. feat: display version ([#311](https://github.com/Mergifyio/mergify-cli/pull/311))

2023-12-26 09:47 UTC, Greesb approved these changes

2023-12-26 18:58 UTC, jd requested changes

2023-12-26 18:58 UTC, jd commented on mergify_cli/__init__.py
> +    parser.add_argument("--version", "-V", action="store_true", help="display version")
There is an `action` version that should be better for this.

2023-12-27 19:34 UTC, jd approved these changes

2023-12-29 12:59 UTC, merged