feat: allow to keep previous title+body
Mergifyio/mergify-cli pull request #370
Opened 2024-04-05 17:26 UTC by sileht

People may edit pull request title and description on GitHub.

mergify stack always erase them.

This change adds an option to never edit them.

2024-04-06 08:31 UTC, jd requested changes

2024-04-06 08:31 UTC, jd commented on mergify_cli/__init__.py
> +    keys_pull_request_title_and_body: bool,
"keys"?

2024-04-06 09:56 UTC, sileht commented on mergify_cli/__init__.py
> +    keys_pull_request_title_and_body: bool,
I didn't write this code :)

2024-04-08 07:07 UTC, jd approved these changes

2024-04-08 07:08 UTC, merged